# Generated by Django 4.2.4 on 2023-08-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='comlete',
            new_name='completed',
        ),
    ]
